#!/usr/bin/env bash
set -euo pipefail

service_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
project_dir="$(cd "$service_dir/../.." && pwd)"
contract="$project_dir/contracts/openapi/public-v1.yaml"
generated_dir="$service_dir/internal/api/generated"
temporary_dir="$(mktemp -d "$service_dir/internal/api/.generated-tmp.XXXXXX")"
backup_dir=""

cleanup() {
  rm -rf "$temporary_dir"
  if [[ -n "$backup_dir" && -d "$backup_dir" && ! -d "$generated_dir" ]]; then
    mv "$backup_dir" "$generated_dir"
  fi
}
trap cleanup EXIT

write_null_support() {
  local target_dir="$1"

  cat > "$target_dir/null.go" <<'EOF'
// Code generated by scripts/generate-openapi.sh. DO NOT EDIT.

package generated

import (
  "bytes"
  "fmt"
)

// Null represents the OpenAPI 3.1 JSON null type without falling back to any.
type Null struct{}

func (Null) MarshalJSON() ([]byte, error) {
  return []byte("null"), nil
}

func (*Null) UnmarshalJSON(data []byte) error {
  if !bytes.Equal(bytes.TrimSpace(data), []byte("null")) {
    return fmt.Errorf("Null accepts only JSON null")
  }
  return nil
}
EOF
  gofmt -w "$target_dir/null.go"
}

npm --prefix "$service_dir" exec -- openapi-generator-cli validate -i "$contract"
npm --prefix "$service_dir" exec -- openapi-generator-cli generate \
  -g go-gin-server \
  -i "$contract" \
  -o "$temporary_dir" \
  --additional-properties=apiPath=internal/api/generated,interfaceOnly=true,packageName=generated,hideGenerationTimestamp=true \
  --type-mappings null=Null \
  --global-property apiTests=false,modelTests=false,apiDocs=false,modelDocs=false

new_generated_dir="$temporary_dir/internal/api/generated"
write_null_support "$new_generated_dir"
find "$new_generated_dir" -name '*.go' -print0 | xargs -0 gofmt -w

if [[ -d "$generated_dir" ]]; then
  backup_dir="$(mktemp -d "$service_dir/internal/api/.generated-backup.XXXXXX")"
  rmdir "$backup_dir"
  mv "$generated_dir" "$backup_dir"
fi
mv "$new_generated_dir" "$generated_dir"

if ! (cd "$service_dir" && go test ./internal/api/generated); then
  rm -rf "$generated_dir"
  if [[ -n "$backup_dir" && -d "$backup_dir" ]]; then
    mv "$backup_dir" "$generated_dir"
  fi
  exit 1
fi

rm -rf "$backup_dir"
backup_dir=""
